'use client';
/* oxlint-disable next/no-img-element -- Photos are already resized and encoded as WebP for this static publication. */
import {useCallback,useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {ArrowUpRight,ArrowLeft,ArrowRight,Menu,Pause,Play,X,Expand} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import data from './journal-data.json';
import {StoryContent} from './story-content';
const photo=(n:number)=>`/photos/${n}.webp`;
const motionQuery='(prefers-reduced-motion: reduce)';
const subscribeMotion=(notify:()=>void)=>{const q=matchMedia(motionQuery);q.addEventListener('change',notify);return()=>q.removeEventListener('change',notify)};
const getReducedMotion=()=>matchMedia(motionQuery).matches;
const getServerReducedMotion=()=>true;
export default function Home(){
 const [page,setPage]=useState(0),[menu,setMenu]=useState(false),[story,setStory]=useState(false),[light,setLight]=useState<number|null>(null),[motionOverride,setMotion]=useState<boolean|null>(null);
 const reducedMotion=useSyncExternalStore(subscribeMotion,getReducedMotion,getServerReducedMotion),motion=motionOverride??!reducedMotion;
 const touch=useRef<{x:number;y:number}|null>(null),current=page?data[page-1]:null;
 const move=useCallback((d:number)=>setPage(p=>Math.min(data.length,Math.max(0,p+d))),[]);
 const changePhoto=useCallback((d:number)=>{if(light===null||!current)return;setLight(current.photos[(current.photos.indexOf(light)+d+current.photos.length)%current.photos.length])},[light,current]);
 useEffect(()=>{function key(e:KeyboardEvent){if((e.target as HTMLElement).matches('input,textarea'))return;if(light!==null){if(e.key==='ArrowLeft'){e.preventDefault();changePhoto(-1)}if(e.key==='ArrowRight'){e.preventDefault();changePhoto(1)}return}if(story||menu)return;if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[light,story,menu,changePhoto,move]);
 return <main className={`journal ${motion?'motion':'still'} theme-${current?.color||'lime'}`}>
 <header className="masthead"><button className="wordmark" onClick={()=>setPage(0)}>360<span>教育在线</span></button><span className="issue">2026 夏季刊 <i>SUMMER JOURNAL</i></span><div className="head-actions"><button aria-label={motion?'关闭动效':'开启动效'} title={motion?'关闭动效':'开启动效'} aria-pressed={motion} onClick={()=>setMotion(!motion)}>{motion?<Pause size={18}/>:<Play size={18}/>}</button><button onClick={()=>setMenu(true)} aria-label="打开目录"><Menu size={20}/><span>目录</span></button></div></header>
 <div className={`spread ${current?.id||'cover'}`} key={page} onTouchStart={e=>{touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(!touch.current||story||menu||light!==null)return;const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.5)move(dx<0?1:-1);touch.current=null}}>
 {!current?<><div className="cover-copy"><p className="overline"><span className="live-dot"/> OUR SUMMER, TOGETHER</p><h1>盛夏<span className="outline">我们</span><span className="accent-word">在场.</span></h1><div className="cover-intro"><p>融通中外 · 研途新篇</p><p>院校之间，城市之间，你我之间。<br/>每一次奔赴，都值得被记住。</p></div><button className="read-button" onClick={()=>setPage(1)}>翻开这个夏天<ArrowRight size={21}/></button></div><div className="cover-images"><div className="cover-main"><img src={photo(7)} alt="创始人付嘉在福州峰会现场分享"/><span className="image-label">01 / 连接院校</span></div><div className="cover-second"><img src={photo(77)} alt="伙伴们的夏日旅行合影"/><span className="image-label">09 / 把生活交还给山海</span></div><div className="cover-type" aria-hidden="true">SUMMER<br/>IN MOTION ↗</div><span className="year-stamp">20<br/>26</span></div></>:<><div className="chapter-copy"><p className="overline">{current.kicker}</p><h1>{current.title.split('\n').map((x,i)=><span key={x} className={i?'accent-word':''}>{x}</span>)}</h1><p className="chapter-desc">{current.desc}</p>{current.id==='content'&&<div className="small-metrics"><span><b>1,064</b>赞</span><span><b>342</b>收藏</span><span><b>67</b>评论</span><small>按本期资料三条内容加总</small></div>}<button className="read-button" onClick={()=>setStory(true)}>阅读故事<span className="photo-count">{current.photos.length} 张照片</span><ArrowUpRight size={22}/></button><div className="chapter-tags">{current.notes.slice(0,3).map(n=><span key={n.name}>{n.name.split(' · ')[0]}</span>)}</div></div><button className={`chapter-image ${['content','warm','people'].includes(current.id)?'contain':''}`} onClick={()=>setLight(current.cover)} aria-label="放大查看本章照片"><img src={photo(current.cover)} alt={current.notes.find(n=>n.photos.includes(current.cover))?.name||current.kicker}/><span className="image-shade"/><span className="image-label">{current.kicker.split(' / ')[1]} / SUMMER 2026</span><span className="expand-icon"><Expand size={20}/></span><span className="giant-number" aria-hidden="true">{String(page).padStart(2,'0')}</span></button></>}
 </div>
 <footer className="reader-footer"><div className="position"><strong>{String(page).padStart(2,'0')}</strong><span>/ 12</span><span className="position-label">{current?.kicker.split(' / ')[1]||'封面'}</span></div><nav className="page-dots" aria-label="章节跳转">{[null,...data].map((d,i)=><button key={d?.id||'cover'} className={page===i?'active':''} onClick={()=>setPage(i)} aria-label={d?.kicker||'封面'} aria-current={page===i?'page':undefined}/>)}</nav><div className="page-controls"><button onClick={()=>move(-1)} disabled={!page} aria-label="上一页"><ArrowLeft size={22}/></button><button onClick={()=>page===12?setPage(0):move(1)}><span>{page===12?'回到封面':'下一页'}</span><ArrowRight size={22}/></button></div></footer>
 <Sheet open={menu} onOpenChange={setMenu}><SheetContent className="directory-panel" showCloseButton={false}><div className="panel-head"><div><SheetTitle>这个夏天，我们一起经历</SheetTitle><SheetDescription>360教育在线 · 2026夏季刊</SheetDescription></div><button className="circle-button" onClick={()=>setMenu(false)} aria-label="关闭目录"><X/></button></div><div className="directory-grid">{data.map((d,i)=><button key={d.id} onClick={()=>{setPage(i+1);setMenu(false)}}><span>{String(i+1).padStart(2,'0')}</span><div><b>{d.kicker.split(' / ')[1]}</b><p>{d.title.replace('\n','')}</p></div><ArrowUpRight size={19}/></button>)}</div><p className="directory-end">每一次奔赴，都值得被记住。<br/>360教育在线 · 行政中心</p></SheetContent></Sheet>
 <Sheet open={story} onOpenChange={setStory}><SheetContent className={`story-panel theme-${current?.color||'lime'} ${motion?'motion':'still'}`} showCloseButton={false}><div className="panel-head story-toolbar"><div><SheetTitle>{current?.kicker}</SheetTitle><SheetDescription>360教育在线 · 2026夏季刊</SheetDescription></div><button className="story-close" onClick={()=>setStory(false)} aria-label="关闭故事"><span>返回主视觉</span><X size={20}/></button></div>{current&&<StoryContent chapter={current} page={page} onPhoto={setLight} onNext={()=>{setStory(false);setPage(p=>p===data.length?0:p+1)}}/>}</SheetContent></Sheet>
 <Dialog open={light!==null} onOpenChange={open=>{if(!open)setLight(null)}}><DialogContent className="lightbox" showCloseButton={false}><div className="lightbox-top"><div><DialogTitle>{current?.notes.find(n=>n.photos.includes(light||0))?.name||'夏日现场'}</DialogTitle><DialogDescription>{current&&light!==null?`${current.photos.indexOf(light)+1} / ${current.photos.length}`:''}</DialogDescription></div><button className="circle-button" onClick={()=>setLight(null)} aria-label="关闭照片"><X/></button></div>{light!==null&&<img className="full-photo" src={photo(light)} alt={current?.notes.find(n=>n.photos.includes(light))?.name||'夏日照片'}/>}<div className="lightbox-bottom"><button onClick={()=>changePhoto(-1)}><ArrowLeft size={20}/>上一张</button><span>完整画面</span><button onClick={()=>changePhoto(1)}>下一张<ArrowRight size={20}/></button></div></DialogContent></Dialog>
 </main>
}
